name: Test

on:
  push:
    branches:
    - v3_without_conan

jobs:
  cpp:
    name: 'C++ tests'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install bison flex
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
    - uses: actions/cache@v3
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-cpp-0
        restore-keys: |
          ${{ runner.os }}-chocolatey-cpp-
          ${{ runner.os }}-chocolatey-
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: choco install winflexbison3 --version 2.5.18.20190508
    - name: Configure
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DOPENQL_BUILD_TESTS=ON -DOPENQL_BUILD_CPP_STANDALONE_EXAMPLE=ON -DWITH_UNITARY_DECOMPOSITION=OFF
    - name: Build
      run: cmake --build . --parallel 5
      working-directory: build
    - name: Test
      run: ctest -C Debug --output-on-failure
      working-directory: build
    - name: Run cpp standalone example
      if: matrix.os != 'windows-latest'
      run: ./example
      working-directory: build
    - name: Run cpp standalone example
      if: matrix.os == 'windows-latest'
      run: example.exe
      working-directory: build

  python:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel pytest numpy qxelarator
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y swig
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install bison flex swig xquartz
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
    - uses: actions/cache@v3
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-python-1
        restore-keys: |
          ${{ runner.os }}-chocolatey-python-
          ${{ runner.os }}-chocolatey-
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        choco install winflexbison3 --version 2.5.18.20190508
    - name: Select build type
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: echo "OPENQL_BUILD_TYPE=Release" >> $GITHUB_ENV
    - name: Select build type
      if: matrix.os != 'windows-latest'
      run: echo "OPENQL_BUILD_TYPE=Debug" >> $GITHUB_ENV
    - name: Disable unitary decomposition
      if: matrix.os != 'windows-latest'
      run: echo "OPENQL_DISABLE_UNITARY=true" >> $GITHUB_ENV
    - name: Disable unitary decomposition
      if: matrix.os == 'windows-latest'
      run: echo "OPENQL_DISABLE_UNITARY=true" >> $env:GITHUB_ENV
    - name: Build
      env:
        NPROCS: 5
      run: python -m pip install --verbose .
    - name: Test
      run: python -m pytest
